services:
  # service name will be used as image name with a prefix of repo name
  test:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: test-scraper
    environment:
      - PORT=3000
    ports:
      - "80:3000"
    command: ["npm", "run", "start:dev"]